### ISSUE TITLE
ToString Bug

### ISSUE THREAD

**Issue by clarkebowers** [FaustVX/BigFloat#1]
ToString() does not handle values less than 1/10 correctly.

Console.WriteLine(new BigFloat(Math.PI * 1000.0).ToString(4, false));
Console.WriteLine(new BigFloat(Math.PI * 100.0).ToString(4, false));
Console.WriteLine(new BigFloat(Math.PI * 10.0).ToString(4, false));
Console.WriteLine(new BigFloat(Math.PI * 1.0).ToString(4, false));
Console.WriteLine(new BigFloat(Math.PI / 10.0).ToString(4, false));
Console.WriteLine(new BigFloat(Math.PI / 100.0).ToString(4, false));
Console.WriteLine(new BigFloat(Math.PI / 1000.0).ToString(4, false));

Gives the following output
3141.5926
314.1592
31.4159
3.1415
0.3141
0.314 <-- zero after the decimal place lost
0.31 <-- two zeros after the decimal place are lost.

Change the while statement to remove the check for zero decimal.
            while (precision-- > 0) <--
            {
                sb.Append(decimals % 10);
                decimals /= 10;
            }

**Comment by FaustVX** [comment]
I'll test this.

Can you make a pull request for this ?
thanks.

Also, put your code in "code block" with  ` ``` `
